# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Harold\projects\python\Testing\testing\projectdetails.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dlgProjectDetails(object):
    def setupUi(self, dlgProjectDetails):
        dlgProjectDetails.setObjectName("dlgProjectDetails")
        dlgProjectDetails.resize(538, 339)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/logo-blue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        dlgProjectDetails.setWindowIcon(icon)
        self.horizontalLayout = QtWidgets.QHBoxLayout(dlgProjectDetails)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(dlgProjectDetails)
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget.setObjectName("widget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setStyleSheet("background-color: rgb(233, 239, 255);")
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_4.setContentsMargins(30, 20, 30, 20)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lblProjectName = QtWidgets.QLabel(self.widget_3)
        self.lblProjectName.setWordWrap(True)
        self.lblProjectName.setObjectName("lblProjectName")
        self.horizontalLayout_4.addWidget(self.lblProjectName)
        self.verticalLayout_3.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setStyleSheet("")
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_2.setContentsMargins(30, 20, 30, 20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblProjectDetails = QtWidgets.QLabel(self.widget_4)
        self.lblProjectDetails.setObjectName("lblProjectDetails")
        self.verticalLayout_2.addWidget(self.lblProjectDetails)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnClickTest = QtWidgets.QPushButton(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnClickTest.sizePolicy().hasHeightForWidth())
        self.btnClickTest.setSizePolicy(sizePolicy)
        self.btnClickTest.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnClickTest.setAutoFillBackground(False)
        self.btnClickTest.setStyleSheet("color: black;\n"
"background-color: rgb(240, 240, 240);\n"
"\n"
"\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/btn_test_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnClickTest.setIcon(icon1)
        self.btnClickTest.setIconSize(QtCore.QSize(30, 30))
        self.btnClickTest.setAutoDefault(True)
        self.btnClickTest.setDefault(False)
        self.btnClickTest.setFlat(False)
        self.btnClickTest.setObjectName("btnClickTest")
        self.horizontalLayout_3.addWidget(self.btnClickTest)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.btnClickPlay = QtWidgets.QPushButton(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnClickPlay.sizePolicy().hasHeightForWidth())
        self.btnClickPlay.setSizePolicy(sizePolicy)
        self.btnClickPlay.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnClickPlay.setStyleSheet("color: black;\n"
"background-color: rgb(240, 240, 240);\n"
"\n"
"\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/btn_play _icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnClickPlay.setIcon(icon2)
        self.btnClickPlay.setIconSize(QtCore.QSize(30, 30))
        self.btnClickPlay.setDefault(False)
        self.btnClickPlay.setFlat(False)
        self.btnClickPlay.setObjectName("btnClickPlay")
        self.horizontalLayout_3.addWidget(self.btnClickPlay)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setStyleSheet("background-color: rgb(233, 239, 255);")
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_6.setContentsMargins(30, 20, 30, 20)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.widget_5)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.verticalLayout_3.addWidget(self.widget_5)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.horizontalLayout_7.addWidget(self.widget_2)
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi(dlgProjectDetails)
        QtCore.QMetaObject.connectSlotsByName(dlgProjectDetails)

    def retranslateUi(self, dlgProjectDetails):
        _translate = QtCore.QCoreApplication.translate
        dlgProjectDetails.setWindowTitle(_translate("dlgProjectDetails", "Dialog"))
        self.lblProjectName.setText(_translate("dlgProjectDetails", "Project Name"))
        self.lblProjectDetails.setText(_translate("dlgProjectDetails", "<html><head/><body><p>Path: c: \\xampp\\users\\doc.exe</p><p>Created at: 2017-03-12</p></body></html>"))
        self.btnClickTest.setText(_translate("dlgProjectDetails", "Test"))
        self.btnClickPlay.setText(_translate("dlgProjectDetails", "Play"))
        self.label_2.setText(_translate("dlgProjectDetails", "© Developed by UGO, Inc."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dlgProjectDetails = QtWidgets.QDialog()
    ui = Ui_dlgProjectDetails()
    ui.setupUi(dlgProjectDetails)
    dlgProjectDetails.show()
    sys.exit(app.exec_())

